/**
 * One-time, NON-DESTRUCTIVE import of a pre-Phase-4 `localStorage` board into the SQLite
 * database (MVP 4.4, `docs/plans/phase-4-plan.md` §5). Runs once, from `board-store.ts`'s boot
 * sequence, only when the database has no `board` rows yet.
 *
 * Two responsibilities are split into two functions on purpose:
 *
 * - `buildSeedCommands` is pure and deterministic (no I/O, no id/timestamp generation of its
 *   own) so it is unit-testable without a database or a browser. It always seeds exactly the two
 *   boards Phase 2/3 knew about — "Redraft PPR" and "Dynasty Superflex" — either from a legacy
 *   `PersistedState` (order reconciled, drafted carried over, filters/preferences copied into
 *   `setSetting` commands) or, when there is nothing to migrate, from a fresh `initialOrder`.
 * - `readLegacyState` does the one bit of I/O and fold-in of failure this module owns: it reads
 *   `localStorage` through the EXISTING `loadPersistedState` (so the v1->v2 migration in
 *   `persistence.ts` is inherited for free — this file does not parse the blob a second time),
 *   and reports whether the legacy key is still present.
 *
 * **The `localStorage` key is never cleared here, or anywhere in this module.** It is the only
 * rollback path for a user mid-migration to a storage engine they cannot inspect (OPFS). Clearing
 * it is a deliberate, later, user-initiated action (Stage D/E) — this module only ever reads it.
 *
 * **A `PersistedStateError` from a corrupt legacy key must not block boot.** A half-parseable
 * `localStorage` blob is a leftover from a PREVIOUS version of the app, not the live store this
 * boot is trying to open — refusing to boot the (empty, otherwise-healthy) database over it would
 * make a corrupt Phase-3 artifact take down Phase 4 for no reason. So this is the one place in
 * the codebase that downgrades a fail-fast `PersistedStateError` into a non-blocking signal:
 * `readLegacyState` catches it, returns `persisted: null` (falling through to a fresh cold
 * start), and hands the message back for `board-store.ts` to surface as `persistenceError` — a
 * visible banner, not a swallowed error. Every other error type still propagates uncaught.
 */
import { createBoardMeta, initialOrder, reconcileOrder, renormalise, type Format } from '@/domain';
import type { BoardPlayerRow, DbCommand } from './db';
import {
  loadPersistedState,
  PersistedStateError,
  STORAGE_KEY,
  type PersistedState,
} from './persistence';
import { getRankings } from './rankings';

/** Ids and timestamp for the two seeded boards — generated by the caller (`board-store.ts`, via
 * `crypto.randomUUID()` / `new Date().toISOString()`) so this function stays pure. */
export interface SeedBoardIds {
  readonly redraftPprId: string;
  readonly dynastySfId: string;
  readonly createdAt: string;
}

const SEED_NAMES: Record<Format, string> = {
  'redraft-ppr': 'Redraft PPR',
  'dynasty-sf': 'Dynasty Superflex',
};

function requireSortOrder(sortKeys: ReadonlyMap<string, number>, playerId: string): number {
  const sortOrder = sortKeys.get(playerId);
  if (sortOrder === undefined) {
    throw new Error(`buildSeedCommands: renormalise produced no key for player "${playerId}".`);
  }
  return sortOrder;
}

function buildSeedBoardCommand(
  id: string,
  format: Format,
  createdAt: string,
  persisted: PersistedState | null
): DbCommand {
  const players = getRankings(format).players;
  const order = persisted
    ? reconcileOrder(persisted.boards[format].order, players)
    : initialOrder(players);
  const sortKeys = renormalise(order);
  const draftedIds = new Set(persisted?.boards[format].drafted ?? []);

  const rows: BoardPlayerRow[] = order.map((playerId) => ({
    playerId,
    sortOrder: requireSortOrder(sortKeys, playerId),
    drafted: draftedIds.has(playerId),
    watched: false,
    tierBreak: false,
    note: null,
  }));

  return {
    kind: 'createBoard',
    board: createBoardMeta(id, SEED_NAMES[format], format, createdAt),
    rows,
  };
}

/**
 * The commands that seed a brand-new database. Always creates both "Redraft PPR" and "Dynasty
 * Superflex". `persisted === null` seeds each from the dataset's own `baseRank` order with
 * nothing drafted and no settings beyond the documented defaults (a genuine cold start).
 * `persisted` non-null carries its `order` (reconciled against the current dataset) and
 * `drafted` set into the matching board, and its `filters`/`preferences`/`activeFormat` into
 * `setSetting` commands.
 *
 * The two boards get DISTINCT `created_at` values (`ids.createdAt`, then that same instant plus
 * one millisecond) even though they are seeded in the same instant — `boardIds`' documented
 * display order is "createdAt, then id" (`board-store.ts`), and `id` is a random UUID. Sharing
 * one timestamp for both would make the default active board (`boardIds[0]`, absent an explicit
 * `activeBoardId` setting) depend on how two random UUIDs happen to compare — nondeterministic
 * across otherwise-identical boots. Deriving the second timestamp from the first keeps this
 * function pure (no extra clock read) while making "Redraft PPR always sorts first" a guarantee
 * rather than a coin flip.
 */
export function buildSeedCommands(
  persisted: PersistedState | null,
  ids: SeedBoardIds
): DbCommand[] {
  const dynastyCreatedAt = new Date(Date.parse(ids.createdAt) + 1).toISOString();
  const commands: DbCommand[] = [
    buildSeedBoardCommand(ids.redraftPprId, 'redraft-ppr', ids.createdAt, persisted),
    buildSeedBoardCommand(ids.dynastySfId, 'dynasty-sf', dynastyCreatedAt, persisted),
  ];

  if (persisted) {
    const activeBoardId =
      persisted.activeFormat === 'redraft-ppr' ? ids.redraftPprId : ids.dynastySfId;
    commands.push(
      { kind: 'setSetting', key: 'activeBoardId', value: activeBoardId },
      { kind: 'setSetting', key: 'theme', value: persisted.preferences.theme },
      { kind: 'setSetting', key: 'density', value: persisted.preferences.density },
      { kind: 'setSetting', key: 'filterPosition', value: persisted.filters.position },
      {
        kind: 'setSetting',
        key: 'filterAvailableOnly',
        value: String(persisted.filters.availableOnly),
      }
    );
  }

  return commands;
}

/** What `readLegacyState` found. `error` is set (and `persisted` is `null`) exactly when the
 * legacy key existed but could not be parsed — see the file header for why that does not throw. */
export interface LegacyState {
  persisted: PersistedState | null;
  /** True iff `localStorage[STORAGE_KEY]` is still present, parseable or not — Stage D/E's
   * one-click "clear my old backup" affordance is offered exactly when this is true. */
  legacyBackupPresent: boolean;
  /** The corrupt-legacy-key message to surface as `persistenceError`, or `null` when nothing
   * was wrong (including when there was nothing to read at all). */
  error: string | null;
}

/** Reads the legacy `localStorage` board through `loadPersistedState` (inheriting its v1->v2
 * migration for free) without ever throwing — see the file header's "downgraded throw" note. */
export function readLegacyState(storage: Storage): LegacyState {
  const legacyBackupPresent = storage.getItem(STORAGE_KEY) !== null;

  try {
    return { persisted: loadPersistedState(storage), legacyBackupPresent, error: null };
  } catch (error) {
    if (error instanceof PersistedStateError) {
      return { persisted: null, legacyBackupPresent, error: error.message };
    }
    throw error;
  }
}
